profiles:
  pokemon:
    prefix: 宝可梦
    prefix-position: first
    separator: "-"
    add-flag: true
    preserve-multiplier: true
    collapse-single: true
    preserve-tags:
      - 直连
      - IPLC
      - IEPL
      - 专线
      - Vless
      - Anytls
      - 家宽
      - 原生
      - V6
      - 游戏
      - 测试
      - AWS

  self_hosted:
    prefix: 自建
    prefix-position: first
    separator: "-"
    add-flag: true
    preserve-multiplier: false
    collapse-single: true
    preserve-tags:
      - 直连
      - IPLC
      - IEPL
      - 专线
      - 中转
      - XHTTP
      - cdn
      - REALITY
      - tls
      - down
      - 家宽
      - 原生
      - V6
      - 游戏
      - 测试
      - AWS
      - BWH
      - DMIT
      - vircs
      - MEGABOX
      - proWee
      - ebCorona
