default-profile: standard

defaults:
  fields: [subscription, flag, iso, protocol, traits, multiplier, sequence]
  separator: " "
  brackets: [subscription, protocol]
  subscription-fallback: null
  extra-traits: []
  sequence: always

profiles:
  standard: {}
  airport:
    extra-traits: [AWS]
  self_hosted:
    subscription-fallback: 自建
    extra-traits: [AWS, BWH, DMIT, vircs, MEGABOX, proWee, ebCorona, down]
