regions:
  - { id: HK, group-name: "🇭🇰 香港", type: select }
  - { id: TW, group-name: "🇹🇼 台湾", type: select }
  - { id: JP, group-name: "🇯🇵 日本", type: select }
  - { id: SG, group-name: "🇸🇬 新加坡", type: select }
  - { id: US, group-name: "🇺🇸 美国", type: select }
  - { id: KR, group-name: "🇰🇷 韩国", type: select }
  - { id: GB, group-name: "🇬🇧 英国", type: select }
  - { id: DE, group-name: "🇩🇪 德国", type: select }
  - { id: FR, group-name: "🇫🇷 法国", type: select }
  - { id: CA, group-name: "🇨🇦 加拿大", type: select }
  - { id: AU, group-name: "🇦🇺 澳大利亚", type: select }
  - { id: RU, group-name: "🇷🇺 俄罗斯", type: select }
  - { id: IN, group-name: "🇮🇳 印度", type: select }
  - { id: MO, group-name: "🇲🇴 澳门", type: select }
  - { id: NZ, group-name: "🇳🇿 新西兰", type: select }
  - { id: IT, group-name: "🇮🇹 意大利", type: select }
  - { id: NL, group-name: "🇳🇱 荷兰", type: select }
  - { id: PL, group-name: "🇵🇱 波兰", type: select }
  - { id: CH, group-name: "🇨🇭 瑞士", type: select }
  - { id: VN, group-name: "🇻🇳 越南", type: select }
  - { id: TH, group-name: "🇹🇭 泰国", type: select }
  - { id: PH, group-name: "🇵🇭 菲律宾", type: select }
  - { id: MY, group-name: "🇲🇾 马来西亚", type: select }
  - { id: ID, group-name: "🇮🇩 印尼", type: select }
  - { id: TR, group-name: "🇹🇷 土耳其", type: select }
  - { id: AR, group-name: "🇦🇷 阿根廷", type: select }
  - { id: BR, group-name: "🇧🇷 巴西", type: select }
  - { id: OTHER, group-name: "🏳️ 其他", type: select }
